language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-compute-io' ]; then cd .. && eval "mv $currentfolder generator-compute-io" && cd generator-compute-io; fi
after_script:
  - npm run coveralls

