language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - '0.8'
  - 'iojs'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-compute-io' ]; then cd .. && eval "mv $currentfolder generator-compute-io" && cd generator-compute-io; fi
  - npm update -g npm
after_script:
  - npm run coveralls

